name: Build
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-02-27
          components: miri,rust-src
      - run: cargo install cargo-careful
      - run: cargo miri test --all-features
      - run: cargo careful test --all-features
      - run: cargo doc --no-deps --all-features
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: target/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
